baseURL = "https://placeholder.dev/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  description = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
