baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"
favicon = "favicon.svg"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  description = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 30

[params.profileMode]
  enabled = true
  title = "CherryPicked"
  subtitle = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"
  buttons = [
    { name = "LinkedIn", url = "https://www.linkedin.com/in/ehsanmsd/" },
    { name = "GitHub", url = "https://github.com/azimmsd" },
    { name = "Posts", url = "/posts/" }
  ]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
