baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"
favicon = "favicon.svg"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  description = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 25

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 30

[params.profileMode]
  enabled = true
  title = "CherryPicked"
  subtitle = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"
  buttons = [
    { name = "Posts", url = "/posts/" }
  ]

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "rss"
  url = "/posts/index.xml"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
