baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"
defaultContentLanguage = "en"
enableEmoji = true

[outputs]
  home = ["HTML", "RSS"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = "posts"
        name = "Posts"
        pageRef = "/en/posts"
        weight = 10
      [[languages.en.menus.main]]
        identifier = "tags"
        name = "Tags"
        pageRef = "/en/tags"
        weight = 25
      [[languages.en.menus.main]]
        identifier = "cv"
        name = "CV"
        pageRef = "/en/cv"
        weight = 30

  [languages.fa]
    languageName = "فارسی"
    weight = 2
    [languages.fa.menus]
      [[languages.fa.menus.main]]
        identifier = "posts"
        name = "مقالات"
        pageRef = "/fa/posts"
        weight = 10
      [[languages.fa.menus.main]]
        identifier = "tags"
        name = "برچسب‌ها"
        pageRef = "/fa/tags"
        weight = 25
      [[languages.fa.menus.main]]
        identifier = "cv"
        name = "سوابق کاری"
        pageRef = "/fa/cv"
        weight = 30

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowToc = true
  mainSections = ["posts"]
  defaultTheme = "auto"
  description = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[params.homeInfoParams]
  title = "CherryPicked"
  content = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "cv"
  url = "/cv/"
