baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"
enableEmoji = true
defaultContentLanguage = "en"

[outputs]
  home = ["HTML", "RSS"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "CherryPicked"
    [languages.en.params]
      [languages.en.params.homeInfoParams]
        title = "CherryPicked"
        content = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Posts"
        url = "/posts/"
        weight = 10
      [[languages.en.menus.main]]
        name = "Tags"
        url = "/tags/"
        weight = 25
      [[languages.en.menus.main]]
        name = "CV"
        url = "/cv/"
        weight = 30

  [languages.fa]
    languageName = "فارسی"
    weight = 2
    title = "CherryPicked"
    [languages.fa.params]
      [languages.fa.params.homeInfoParams]
        title = "CherryPicked"
        content = "یادداشت‌های برگزیده از زندگی، فلسفه، سینما، ادبیات، سیاست و فناوری"
    [languages.fa.menus]
      [[languages.fa.menus.main]]
        name = "مقالات"
        url = "/fa/posts/"
        weight = 10
      [[languages.fa.menus.main]]
        name = "برچسب‌ها"
        url = "/fa/tags/"
        weight = 25
      [[languages.fa.menus.main]]
        name = "سوابق کاری"
        url = "/cv/"
        weight = 30

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowToc = true
  mainSections = ["posts"]
  defaultTheme = "auto"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "cv"
  url = "/cv/"

[caches]
