baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked ğŸ’"
theme = "PaperMod"
enableEmoji = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML", "RSS"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 25
    [[languages.en.menu.main]]
      name = "CV"
      url = "/cv/"
      weight = 30

  [languages.fa]
    languageName = "ÙØ§Ø±Ø³ÛŒ"
    weight = 2
    contentDir = "content/fa"
    [[languages.fa.menu.main]]
      name = "Ù†ÙˆØ´ØªÙ‡â€ŒÙ‡Ø§"
      url = "/fa/posts/"
      weight = 10
    [[languages.fa.menu.main]]
      name = "Ø¨Ø±Ú†Ø³Ø¨â€ŒÙ‡Ø§"
      url = "/fa/tags/"
      weight = 25
    [[languages.fa.menu.main]]
      name = "Ø±Ø²ÙˆÙ…Ù‡"
      url = "/fa/cv/"
      weight = 30

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowToc = true
  mainSections = ["posts"]
  defaultTheme = "auto"

[params.homeInfoParams]
  title = "CherryPicked ğŸ’"
  content = "Cherry-picked is my self-portrait. Notes from life, tech, philosophy, literature, and politics."
  imageUrl = "myprofile.png"  # path to your profile image in the static folder (without leading slash)
  imageWidth = 150
  imageHeight = 150
  imageTitle = "Profile Image"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "cv"
  url = "/cv/"

[caches]
