baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked"
theme = "PaperMod"
enableEmoji = true


[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 25
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 30

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowToc = true
  mainSections = ["posts"]
  defaultTheme = "auto"

[params.homeInfoParams]
  title = "CherryPicked"
  content = "Cherry-picked notes from life, philosophy, cinema, literature, politics, and tech"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "cv"
  url = "/cv/"
