baseURL = "https://cherrypicked.me/"
languageCode = "en-us"
title = "CherryPicked ğŸ’"
theme = "PaperMod"
enableEmoji = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML", "RSS"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params.homeInfoParams]
      title = "CherryPicked ğŸ’"
      content = "CherryPicked is my self-portrait. Notes from life, tech, philosophy, literature, and politics."
      imageUrl = "myprofile.png"
      imageWidth = 150
      imageHeight = 150
      imageTitle = "Profile Image"
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 10
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 25
    [[languages.en.menu.main]]
      name = "CV"
      url = "/cv/"
      weight = 30

  [languages.fa]
    languageName = "ÙØ§Ø±Ø³ÛŒ"
    weight = 2
    contentDir = "content/fa"
    [languages.fa.params.homeInfoParams]
      title = "ğŸ’ Ø¢Ù„Ø¨Ø§Ù„ÙˆÚ†ÛŒÙ†"
      content = "Ø¢Ù„Ø¨Ø§Ù„ÙˆÚ†ÛŒÙ† ÛŒÚ© Ø®ÙˆØ¯Ù†Ú¯Ø§Ø±Ù‡ Ø§Ø³Øª. Ù…Ù† Ø§ÛŒÙ†Ø¬Ø§ Ø¨Ø±Ø¯Ø§Ø´Øªâ€ŒÙ‡Ø§Ù… Ø¯Ø±Ø¨Ø§Ø±Ù‡â€ŒÛŒ Ø²Ù†Ø¯Ú¯ÛŒØŒ ØªÚ©Ù†ÙˆÙ„ÙˆÚ˜ÛŒØŒ Ø§Ø¯Ø¨ÛŒØ§ØªØŒ ÙÙ„Ø³ÙÙ‡ Ùˆ Ø³ÛŒØ§Ø³Øª Ø±Ùˆ Ù†Ú¯Ø§Ø±Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ù…."
      imageUrl = "myprofile.png"
      imageWidth = 150
      imageHeight = 150
      imageTitle = "ØªØµÙˆÛŒØ± Ù¾Ø±ÙˆÙØ§ÛŒÙ„"
    [[languages.fa.menu.main]]
      name = "Ù†ÙˆØ´ØªÙ‡â€ŒÙ‡Ø§"
      url = "/fa/posts/"
      weight = 10
    [[languages.fa.menu.main]]
      name = "Ø¨Ø±Ú†Ø³Ø¨â€ŒÙ‡Ø§"
      url = "/fa/tags/"
      weight = 25
    [[languages.fa.menu.main]]
      name = "Ø±Ø²ÙˆÙ…Ù‡"
      url = "/fa/cv/"
      weight = 30

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowToc = true
  mainSections = ["posts"]
  defaultTheme = "auto"


[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ehsanmsd/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/azimmsd"

[[params.socialIcons]]
  name = "cv"
  url = "/cv/"

[caches]
